# Generated by Django 5.2.4 on 2026-02-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='URL de la foto de perfil (Google u otra)', null=True),
        ),
    ]
