# Generated by Django 5.2.4 on 2026-02-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_url',
            field=models.URLField(blank=True, help_text='URL de la imagen de fondo', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cursor_url',
            field=models.URLField(blank=True, help_text='URL del cursor personalizado (.cur o .png)', max_length=500, null=True),
        ),
    ]
