# Generated by Django 5.2.4 on 2026-02-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_background_url_userprofile_cursor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cursor_hotspot_x',
            field=models.IntegerField(default=16, help_text='Posición X del punto de clic'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cursor_hotspot_y',
            field=models.IntegerField(default=16, help_text='Posición Y del punto de clic'),
        ),
    ]
