# Generated by Django 5.2.4 on 2026-02-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_cursor_hotspot_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cursor_blocked_url',
            field=models.URLField(blank=True, help_text='URL del cursor blocked personalizado (.cur o .png)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cursor_pointer_url',
            field=models.URLField(blank=True, help_text='URL del cursor pointer personalizado (.cur o .png)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cursor_text_url',
            field=models.URLField(blank=True, help_text='URL del cursor text personalizado (.cur o .png)', max_length=500, null=True),
        ),
    ]
