# Generated by Django 5.2.4 on 2026-02-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_cursor_blocked_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cursor_url',
            field=models.URLField(blank=True, default='https://cdn.cursors-4u.net/css-previews/naruto-uzumaki-shoulder-pump-778e34fa-css.webp', help_text='URL del cursor personalizado (.cur o .png)', max_length=500, null=True),
        ),
    ]
