# Generated by Django 5.2.4 on 2026-02-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_cursor_blocked_hotspot_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
    ]
