# Generated by Django 5.2.4 on 2026-02-06 16:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentslikes', '0002_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('safe', 'Safe'), ('nsfw', 'NSFW')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
