# Generated by Django 5.2.4 on 2026-02-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentslikes', '0003_comment_image_status_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('safe', 'Safe'), ('nsfw', 'NSFW')], default='pending', max_length=10, null=True),
        ),
    ]
