# Generated by Django 5.2.4 on 2026-02-09 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Header')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Imagen Principal')),
                ('main_paragraph', models.TextField(verbose_name='Párrafo Principal (Intro)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtítulo')),
                ('content', models.TextField(verbose_name='Contenido del tema')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='a_blog.blogpost')),
            ],
            options={
                'verbose_name': 'Sub-tema',
                'verbose_name_plural': 'Sub-temas',
                'ordering': ['order'],
            },
        ),
    ]
