# Generated by Django 5.2.4 on 2026-02-11 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0003_alter_blogpost_main_image_alter_tag_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='a_blog.blogpost')),
            ],
            options={
                'verbose_name': 'Estadística Diaria',
                'verbose_name_plural': 'Estadísticas Diarias',
                'ordering': ['-date'],
                'unique_together': {('post', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BlogPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='a_blog.blogpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vista de Blog',
                'verbose_name_plural': 'Vistas de Blog',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['post', '-viewed_at'], name='a_blog_blog_post_id_5142eb_idx'), models.Index(fields=['ip_address', 'post'], name='a_blog_blog_ip_addr_dd0662_idx')],
            },
        ),
    ]
