# Generated by Django 5.2.4 on 2026-02-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='cv',
        ),
    ]
