# Generated by Django 5.2.4 on 2025-08-26 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('modalidad', models.CharField(blank=True, choices=[('Presencial', 'presencial'), ('Virtual', 'Virtual')], null=True)),
                ('day', models.CharField(blank=True, choices=[('mon', 'Lunes'), ('tue', 'Martes'), ('wed', 'Miércoles'), ('thu', 'Jueves'), ('fri', 'Viernes'), ('sat', 'Sábado'), ('sun', 'Domingo')], max_length=10, null=True, verbose_name='Dia')),
                ('hour', models.CharField(blank=True, choices=[('08:00', '08:00 AM'), ('10:00', '10:00 AM'), ('12:00', '12:00 PM'), ('14:00', '02:00 PM'), ('16:00', '04:00 PM'), ('18:00', '06:00 PM'), ('20:00', '08:00 PM')], max_length=5, null=True, verbose_name='Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='schedules.teacher', verbose_name='Profesor')),
            ],
        ),
    ]
