# Generated by Django 5.2.4 on 2026-02-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('Presencial', 'presencial'), ('Virtual', 'Virtual')], max_length=50, null=True),
        ),
    ]
