# Generated by Django 5.2.4 on 2026-02-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_subject_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_aproved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
